source "https://rubygems.org"
gemspec
gem "jekyll", "= 3.9.2"

gem "webrick", "~> 1.7"

gem "kramdown-parser-gfm", "~> 1.1"

gem "sass-embedded", "~> 1.57"

gem "wdm", "~> 0.1.1"

gem 'bootstrap', '~> 5.2.2'